In [1]:
import pandas as pd
import numpy as np

# Paso 1: Crear un DataFrame de 20x20 con valores aleatorios
np.random.seed(0)  # Para reproducibilidad
data = np.random.randint(1, 500, size=(20, 20))  # Valores aleatorios entre 1 y 500
columns = [f'Col_{i+1}' for i in range(20)]  # Nombres de columnas Col_1, Col_2, ..., Col_20
df = pd.DataFrame(data, columns=columns)

# Paso 2: Mostrar el DataFrame
print("DataFrame original:")
print(df)

# Paso 3: Aleatoriamente eliminar 5 datos de toda la data
# Vamos a eliminar 5 valores aleatorios del DataFrame.
np.random.seed(1)  # Cambiar la semilla para obtener una eliminación diferente
for _ in range(5):
    row = np.random.randint(0, 20)
    col = np.random.randint(0, 20)
    df.iloc[row, col] = np.nan  # Asignar NaN a una posición aleatoria

print("\nDataFrame después de eliminar 5 datos aleatorios (NaN):")
print(df)

# Paso 4: Eliminar las filas con valores nulos
df_cleaned = df.dropna()  # Elimina filas con cualquier NaN
print("\nDataFrame después de eliminar filas con valores nulos:")
print(df_cleaned)

# Paso 5: Agrupar los datos por la columna 'Col_1' y calcular el promedio
# Para esto vamos a crear una columna 'Col_1' con valores aleatorios para simular un agrupamiento.
df['Col_1'] = np.random.randint(1, 6, size=(20))  # Añadimos 'Col_1' con valores entre 1 y 5

grouped = df.groupby('Col_1').mean()  # Agrupar por 'Col_1' y calcular el promedio
print("\nPromedio por grupo de 'Col_1':")
print(grouped)

# Paso 6: Crear una nueva columna 'New_Column' con el producto de 'Col_2' y 'Col_3'
df['New_Column'] = df['Col_2'] * df['Col_3']
print("\nDataFrame con la nueva columna 'New_Column' (producto de 'Col_2' y 'Col_3'):")
print(df)

# Paso 7: Filtrar las filas donde 'New_Column' > 300
df_filtered = df[df['New_Column'] > 300]
print("\nDataFrame después de filtrar las filas donde 'New_Column' > 300:")
print(df_filtered)

# Paso 8: Normalizar las columnas del DataFrame (escala de 0 a 1)
df_normalized = (df - df.min()) / (df.max() - df.min())  # Normalización Min-Max
print("\nDataFrame normalizado:")
print(df_normalized)

# Paso 9: Usar pivot_table para reorganizar y aplicar 5 funciones agregadas
# Para el ejemplo, usaremos 'Col_1' como índice, 'Col_2' como columna y 'New_Column' como valores.
pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})
print("\nPivot Table con 5 funciones agregadas:")
print(pivot)

# Paso 10: Seleccionar las primeras 2 filas y 2 columnas para obtener una matriz 2x2
# Y asegurarnos que todos sus valores sean 5
df_2x2 = df.iloc[:2, :2]  # Seleccionamos las primeras 2 filas y 2 columnas

# Asignamos todos los valores de la matriz 2x2 a 5
df_2x2[:] = 5

print("\nMatriz 2x2 con todos los valores igual a 5:")
print(df_2x2)

# Confirmar que la matriz es de 2x2 y todos sus valores son 5
assert df_2x2.shape == (2, 2), "La matriz no es 2x2."
assert (df_2x2 == 5).all().all(), "No todos los valores son 5."

print("\n¡El resultado es correcto!")

DataFrame original:
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
0     173     48    118    193    324    252    196    360     10     212
1     487     40     88    175     89    338    166     26    334      73
2     100    473    178    244    286    148    148    399    424     289
3     460    371    184     29    291    129    129    421     54     390
4     377    258    322    488    426     58    292    359    120     268
5      85    204    325    263    453     48    128    132    461     357
6     374    342     49    306     70    170    164    449     96     198
7      43    462    369    488    406    202    384      1    395     371
8     223    124    452     83    431    228    149    210     51     412
9     259    308     81     33    183    129    295    276    175      43
10     95    227    364    270    369    297    329     20     96     329
11    452    238    140     87    462    378    110    332    185      17
12    446     84    162    361    417    229    252    122    327     470
13    208    268    167    112    350    130    224    375    301     217
14    215    190    198    216     44     33     12    105    213     139
15    218    152    310    308    175    149    438     30     68      36
16    260    288    266    395     28    430    200    424     62     342
17    257    460    291    198    383    438    255     81    447     137
18    177     26    324    360    292    115    287     30    242     290
19    254    323    112     92    342    424     40    460    151     415

    Col_11  Col_12  Col_13  Col_14  Col_15  Col_16  Col_17  Col_18  Col_19  \
0      278     243     293      88      71     473      89     397     315
1      266     405     116     465     244     198     336     432     449
2      450     266     186     128      33      32     203     245     152
3       39     489     245     274     336     389     106      43     443
4      431      83      92     385     399     100      54     397     122
5      181     489     335     144     149     228     443     280     208
6       95     257     370     179     293     419     305     350     388
7       44     443     384      24     188     131     378      99      63
8      271      42      59     194      37     267      87      44     361
9      372     185     445     489      78     287     281     126     259
10     411     451     249     181     324     493     318     271     353
11     153     414     150     111      26     465     445     378     375
12     288      14     328     185     153      80      42     275      41
13     382      25      68     467     496     260     235     205     487
14     183     492     422     126     157     112     489     259      28
15     296     394      74     298     408     388     303     219     435
16     354      45     291     419      89      34     134     233     256
17     190     130     210     369     292     377     348     169     373
18     147     274     222     341       3      70     358     397      45
19     146     199     456     275     349      44      84     434     298

    Col_20
0      194
1      339
2      164
3       32
4      427
5      398
6       99
7      420
8       12
9        4
10     261
11     118
12     439
13     292
14     468
15     365
16      37
17     293
18     374
19      94

DataFrame después de eliminar 5 datos aleatorios (NaN):
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
0     173     48    118    193    324    252    196    360   10.0     212
1     487     40     88    175     89    338    166     26  334.0      73
2     100    473    178    244    286    148    148    399  424.0     289
3     460    371    184     29    291    129    129    421   54.0     390
4     377    258    322    488    426     58    292    359  120.0     268
5      85    204    325    263    453     48    128    132  461.0     357
6     374    342     49    306     70    170    164    449   96.0     198
7      43    462    369    488    406    202    384      1  395.0     371
8     223    124    452     83    431    228    149    210   51.0     412
9     259    308     81     33    183    129    295    276  175.0      43
10     95    227    364    270    369    297    329     20   96.0     329
11    452    238    140     87    462    378    110    332  185.0      17
12    446     84    162    361    417    229    252    122    NaN     470
13    208    268    167    112    350    130    224    375  301.0     217
14    215    190    198    216     44     33     12    105  213.0     139
15    218    152    310    308    175    149    438     30   68.0      36
16    260    288    266    395     28    430    200    424   62.0     342
17    257    460    291    198    383    438    255     81  447.0     137
18    177     26    324    360    292    115    287     30  242.0     290
19    254    323    112     92    342    424     40    460  151.0     415

    Col_11  Col_12  Col_13  Col_14  Col_15  Col_16  Col_17  Col_18  Col_19  \
0      278   243.0     293      88      71   473.0     NaN     397     315
1      266   405.0     116     465     244   198.0   336.0     432     449
2      450   266.0     186     128      33    32.0   203.0     245     152
3       39   489.0     245     274     336   389.0   106.0      43     443
4      431    83.0      92     385     399   100.0    54.0     397     122
5      181     NaN     335     144     149     NaN   443.0     280     208
6       95   257.0     370     179     293   419.0   305.0     350     388
7       44   443.0     384      24     188   131.0   378.0      99      63
8      271    42.0      59     194      37   267.0    87.0      44     361
9      372     NaN     445     489      78   287.0   281.0     126     259
10     411   451.0     249     181     324   493.0   318.0     271     353
11     153   414.0     150     111      26   465.0   445.0     378     375
12     288    14.0     328     185     153    80.0    42.0     275      41
13     382    25.0      68     467     496   260.0   235.0     205     487
14     183   492.0     422     126     157   112.0   489.0     259      28
15     296   394.0      74     298     408   388.0   303.0     219     435
16     354    45.0     291     419      89    34.0   134.0     233     256
17     190   130.0     210     369     292   377.0   348.0     169     373
18     147   274.0     222     341       3    70.0   358.0     397      45
19     146   199.0     456     275     349    44.0    84.0     434     298

    Col_20
0      194
1      339
2      164
3       32
4      427
5      398
6       99
7      420
8       12
9        4
10     261
11     118
12     439
13     292
14     468
15     365
16      37
17     293
18     374
19      94

DataFrame después de eliminar filas con valores nulos:
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
1     487     40     88    175     89    338    166     26  334.0      73
2     100    473    178    244    286    148    148    399  424.0     289
3     460    371    184     29    291    129    129    421   54.0     390
4     377    258    322    488    426     58    292    359  120.0     268
6     374    342     49    306     70    170    164    449   96.0     198
7      43    462    369    488    406    202    384      1  395.0     371
8     223    124    452     83    431    228    149    210   51.0     412
10     95    227    364    270    369    297    329     20   96.0     329
11    452    238    140     87    462    378    110    332  185.0      17
13    208    268    167    112    350    130    224    375  301.0     217
14    215    190    198    216     44     33     12    105  213.0     139
15    218    152    310    308    175    149    438     30   68.0      36
16    260    288    266    395     28    430    200    424   62.0     342
17    257    460    291    198    383    438    255     81  447.0     137
18    177     26    324    360    292    115    287     30  242.0     290
19    254    323    112     92    342    424     40    460  151.0     415

    Col_11  Col_12  Col_13  Col_14  Col_15  Col_16  Col_17  Col_18  Col_19  \
1      266   405.0     116     465     244   198.0   336.0     432     449
2      450   266.0     186     128      33    32.0   203.0     245     152
3       39   489.0     245     274     336   389.0   106.0      43     443
4      431    83.0      92     385     399   100.0    54.0     397     122
6       95   257.0     370     179     293   419.0   305.0     350     388
7       44   443.0     384      24     188   131.0   378.0      99      63
8      271    42.0      59     194      37   267.0    87.0      44     361
10     411   451.0     249     181     324   493.0   318.0     271     353
11     153   414.0     150     111      26   465.0   445.0     378     375
13     382    25.0      68     467     496   260.0   235.0     205     487
14     183   492.0     422     126     157   112.0   489.0     259      28
15     296   394.0      74     298     408   388.0   303.0     219     435
16     354    45.0     291     419      89    34.0   134.0     233     256
17     190   130.0     210     369     292   377.0   348.0     169     373
18     147   274.0     222     341       3    70.0   358.0     397      45
19     146   199.0     456     275     349    44.0    84.0     434     298

    Col_20
1      339
2      164
3       32
4      427
6       99
7      420
8       12
10     261
11     118
13     292
14     468
15     365
16      37
17     293
18     374
19      94

Promedio por grupo de 'Col_1':
            Col_2       Col_3       Col_4       Col_5       Col_6       Col_7  \
Col_1
1      288.000000  266.000000  395.000000   28.000000  430.000000  200.000000
2      224.285714  219.571429  199.428571  264.428571  220.000000  193.857143
3      227.750000  224.250000  356.250000  320.500000  188.500000  259.250000
4      124.000000  452.000000   83.000000  431.000000  228.000000  149.000000
5      284.714286  192.571429  200.285714  318.428571  196.142857  207.857143

            Col_8       Col_9      Col_10      Col_11      Col_12      Col_13  \
Col_1
1      424.000000   62.000000  342.000000  354.000000   45.000000  291.000000
2      212.428571  169.285714  231.285714  182.714286  317.285714  274.571429
3      237.500000  104.000000  316.250000  306.250000  201.250000  259.750000
4      210.000000   51.000000  412.000000  271.000000   42.000000   59.000000
5      220.142857  325.000000  195.285714  264.000000  310.600000  240.571429

           Col_14      Col_15      Col_16      Col_17      Col_18      Col_19  \
Col_1
1      419.000000   89.000000   34.000000  134.000000  233.000000  256.000000
2      253.000000  230.857143  264.714286  281.333333  274.000000  276.714286
3      232.500000  292.250000  273.000000  179.750000  323.250000  226.000000
4      194.000000   37.000000  267.000000   87.000000   44.000000  361.000000
5      261.142857  173.428571  228.833333  331.571429  252.142857  284.714286

           Col_20
Col_1
1       37.000000
2      260.000000
3      306.500000
4       12.000000
5      247.857143

DataFrame con la nueva columna 'New_Column' (producto de 'Col_2' y 'Col_3'):
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
0       2     48    118    193    324    252    196    360   10.0     212
1       5     40     88    175     89    338    166     26  334.0      73
2       5    473    178    244    286    148    148    399  424.0     289
3       2    371    184     29    291    129    129    421   54.0     390
4       3    258    322    488    426     58    292    359  120.0     268
5       5    204    325    263    453     48    128    132  461.0     357
6       3    342     49    306     70    170    164    449   96.0     198
7       5    462    369    488    406    202    384      1  395.0     371
8       4    124    452     83    431    228    149    210   51.0     412
9       5    308     81     33    183    129    295    276  175.0      43
10      3    227    364    270    369    297    329     20   96.0     329
11      5    238    140     87    462    378    110    332  185.0      17
12      3     84    162    361    417    229    252    122    NaN     470
13      5    268    167    112    350    130    224    375  301.0     217
14      2    190    198    216     44     33     12    105  213.0     139
15      2    152    310    308    175    149    438     30   68.0      36
16      1    288    266    395     28    430    200    424   62.0     342
17      2    460    291    198    383    438    255     81  447.0     137
18      2     26    324    360    292    115    287     30  242.0     290
19      2    323    112     92    342    424     40    460  151.0     415

    ...  Col_12  Col_13  Col_14  Col_15  Col_16  Col_17  Col_18  Col_19  \
0   ...   243.0     293      88      71   473.0     NaN     397     315
1   ...   405.0     116     465     244   198.0   336.0     432     449
2   ...   266.0     186     128      33    32.0   203.0     245     152
3   ...   489.0     245     274     336   389.0   106.0      43     443
4   ...    83.0      92     385     399   100.0    54.0     397     122
5   ...     NaN     335     144     149     NaN   443.0     280     208
6   ...   257.0     370     179     293   419.0   305.0     350     388
7   ...   443.0     384      24     188   131.0   378.0      99      63
8   ...    42.0      59     194      37   267.0    87.0      44     361
9   ...     NaN     445     489      78   287.0   281.0     126     259
10  ...   451.0     249     181     324   493.0   318.0     271     353
11  ...   414.0     150     111      26   465.0   445.0     378     375
12  ...    14.0     328     185     153    80.0    42.0     275      41
13  ...    25.0      68     467     496   260.0   235.0     205     487
14  ...   492.0     422     126     157   112.0   489.0     259      28
15  ...   394.0      74     298     408   388.0   303.0     219     435
16  ...    45.0     291     419      89    34.0   134.0     233     256
17  ...   130.0     210     369     292   377.0   348.0     169     373
18  ...   274.0     222     341       3    70.0   358.0     397      45
19  ...   199.0     456     275     349    44.0    84.0     434     298

    Col_20  New_Column
0      194        5664
1      339        3520
2      164       84194
3       32       68264
4      427       83076
5      398       66300
6       99       16758
7      420      170478
8       12       56048
9        4       24948
10     261       82628
11     118       33320
12     439       13608
13     292       44756
14     468       37620
15     365       47120
16      37       76608
17     293      133860
18     374        8424
19      94       36176

[20 rows x 21 columns]

DataFrame después de filtrar las filas donde 'New_Column' > 300:
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
0       2     48    118    193    324    252    196    360   10.0     212
1       5     40     88    175     89    338    166     26  334.0      73
2       5    473    178    244    286    148    148    399  424.0     289
3       2    371    184     29    291    129    129    421   54.0     390
4       3    258    322    488    426     58    292    359  120.0     268
5       5    204    325    263    453     48    128    132  461.0     357
6       3    342     49    306     70    170    164    449   96.0     198
7       5    462    369    488    406    202    384      1  395.0     371
8       4    124    452     83    431    228    149    210   51.0     412
9       5    308     81     33    183    129    295    276  175.0      43
10      3    227    364    270    369    297    329     20   96.0     329
11      5    238    140     87    462    378    110    332  185.0      17
12      3     84    162    361    417    229    252    122    NaN     470
13      5    268    167    112    350    130    224    375  301.0     217
14      2    190    198    216     44     33     12    105  213.0     139
15      2    152    310    308    175    149    438     30   68.0      36
16      1    288    266    395     28    430    200    424   62.0     342
17      2    460    291    198    383    438    255     81  447.0     137
18      2     26    324    360    292    115    287     30  242.0     290
19      2    323    112     92    342    424     40    460  151.0     415

    ...  Col_12  Col_13  Col_14  Col_15  Col_16  Col_17  Col_18  Col_19  \
0   ...   243.0     293      88      71   473.0     NaN     397     315
1   ...   405.0     116     465     244   198.0   336.0     432     449
2   ...   266.0     186     128      33    32.0   203.0     245     152
3   ...   489.0     245     274     336   389.0   106.0      43     443
4   ...    83.0      92     385     399   100.0    54.0     397     122
5   ...     NaN     335     144     149     NaN   443.0     280     208
6   ...   257.0     370     179     293   419.0   305.0     350     388
7   ...   443.0     384      24     188   131.0   378.0      99      63
8   ...    42.0      59     194      37   267.0    87.0      44     361
9   ...     NaN     445     489      78   287.0   281.0     126     259
10  ...   451.0     249     181     324   493.0   318.0     271     353
11  ...   414.0     150     111      26   465.0   445.0     378     375
12  ...    14.0     328     185     153    80.0    42.0     275      41
13  ...    25.0      68     467     496   260.0   235.0     205     487
14  ...   492.0     422     126     157   112.0   489.0     259      28
15  ...   394.0      74     298     408   388.0   303.0     219     435
16  ...    45.0     291     419      89    34.0   134.0     233     256
17  ...   130.0     210     369     292   377.0   348.0     169     373
18  ...   274.0     222     341       3    70.0   358.0     397      45
19  ...   199.0     456     275     349    44.0    84.0     434     298

    Col_20  New_Column
0      194        5664
1      339        3520
2      164       84194
3       32       68264
4      427       83076
5      398       66300
6       99       16758
7      420      170478
8       12       56048
9        4       24948
10     261       82628
11     118       33320
12     439       13608
13     292       44756
14     468       37620
15     365       47120
16      37       76608
17     293      133860
18     374        8424
19      94       36176

[20 rows x 21 columns]

DataFrame normalizado:
    Col_1     Col_2     Col_3     Col_4     Col_5     Col_6     Col_7  \
0    0.25  0.049217  0.171216  0.357298  0.682028  0.540741  0.431925
1    1.00  0.031320  0.096774  0.318083  0.140553  0.753086  0.361502
2    1.00  1.000000  0.320099  0.468410  0.594470  0.283951  0.319249
3    0.25  0.771812  0.334988  0.000000  0.605991  0.237037  0.274648
4    0.50  0.519016  0.677419  1.000000  0.917051  0.061728  0.657277
5    1.00  0.398210  0.684864  0.509804  0.979263  0.037037  0.272300
6    0.50  0.706935  0.000000  0.603486  0.096774  0.338272  0.356808
7    1.00  0.975391  0.794045  1.000000  0.870968  0.417284  0.873239
8    0.75  0.219239  1.000000  0.117647  0.928571  0.481481  0.321596
9    1.00  0.630872  0.079404  0.008715  0.357143  0.237037  0.664319
10   0.50  0.449664  0.781638  0.525054  0.785714  0.651852  0.744131
11   1.00  0.474273  0.225806  0.126362  1.000000  0.851852  0.230047
12   0.50  0.129754  0.280397  0.723312  0.896313  0.483951  0.563380
13   1.00  0.541387  0.292804  0.180828  0.741935  0.239506  0.497653
14   0.25  0.366890  0.369727  0.407407  0.036866  0.000000  0.000000
15   0.25  0.281879  0.647643  0.607843  0.338710  0.286420  1.000000
16   0.00  0.586130  0.538462  0.797386  0.000000  0.980247  0.441315
17   0.25  0.970917  0.600496  0.368192  0.817972  1.000000  0.570423
18   0.25  0.000000  0.682382  0.721133  0.608295  0.202469  0.645540
19   0.25  0.664430  0.156328  0.137255  0.723502  0.965432  0.065728


<ipython-input-1-847cea387b14>:55: FutureWarning: The provided callable <function mean at 0x79f3a523d5a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})
<ipython-input-1-847cea387b14>:55: FutureWarning: The provided callable <function sum at 0x79f3a523c670> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})
<ipython-input-1-847cea387b14>:55: FutureWarning: The provided callable <function min at 0x79f3a523cdc0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})
<ipython-input-1-847cea387b14>:55: FutureWarning: The provided callable <function max at 0x79f3a523cca0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})
<ipython-input-1-847cea387b14>:55: FutureWarning: The provided callable <function std at 0x79f3a523d6c0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  pivot = df.pivot_table(index='Col_1', values=['Col_2', 'New_Column'], aggfunc={'Col_2': np.mean, 'New_Column': [np.sum, np.min, np.max, np.mean, np.std]})